### ISSUE TITLE
TypeError: tuple indices must be integers or slices, not str

### ISSUE THREAD

**Issue by guangyuzhang** [MyEMS/myems#217]
2022-05-05 03:11:54 [FALCON] [ERROR] GET //reports/meterbatch?spaceid=10000&reportingperiodstartdatetime=2022-05-04T00:00:00&reportingperiodenddatetime=2022-05-05T23:59:59 => Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/falcon/app.py", line 361, in __call__
    responder(req, resp, **params)
  File "/code/reports/meterbatch.py", line 154, in on_get
    energy_category_set.add(row_meter['energy_category_id'])
TypeError: tuple indices must be integers or slices, not str

**Comment by guangyuzhang** [comment]
fixed
