### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by guangyuzhang** [MyEMS/myems#312]
![image](https://user-images.githubusercontent.com/4197169/202843779-f9655d7e-0cfc-4ca9-9556-9f3e874ff8af.png)

2022-11-19 08:55:13 [FALCON] [ERROR] GET //reports/combinedequipmentenergycategory?combinedequipmentid=1000001&periodtype=daily&baseperiodstartdatetime=2022-10-01T00:00:00&baseperiodenddatetime=2022-10-19T16:54:59&reportingperiodstartdatetime=2022-11-01T00:00:00&reportingperiodenddatetime=2022-11-19T16:54:59&language=zh_CN => Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/falcon/app.py", line 365, in __call__
    responder(req, resp, **params)
  File "/code/reports/combinedequipmentenergycategory.py", line 681, in on_get
    associated_report_period['timestamps'].append(associated_report[energy_category_id]['timestamps'])
                                                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 1

**Comment by guangyuzhang** [comment]
fixed
